# -*- coding: utf-8 -*-
"""datasource.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qH7dZuzhBsMTfDnfTPFaY3UFSA_DY2mu
"""

import streamlit as st

if __name__ == "__main__":

    st.title("Data Source")

    st.info("Click on the app name to get the data source")

    st.markdown(
        "- [Early Diabetes Diagnosis](https://archive.ics.uci.edu/ml/datasets/Early+stage+diabetes+risk+prediction+dataset.)"
    )
    st.markdown(
        "- [Liver Disease Prediction](https://www.kaggle.com/datasets/uciml/indian-liver-patient-records))"
    )
    st.markdown(
        "- [Pneumonia Detection](https://www.kaggle.com/datasets/kostasdiamantaras/chest-xrays-bacterial-viral-pneumonia-normal))"
    )
